move /y "CallistoBiomes.DDS~7d678bb (Remastered all biome textures to eliminate DXT errors)" CallistoBiomes.dds
move /y "CeresBiomes.DDS~7d678bb (Remastered all biome textures to eliminate DXT errors)" CeresBiomes.dds
move /y "CharonBiomes.DDS~7d678bb (Remastered all biome textures to eliminate DXT errors)" CharonBiomes.dds
move /y "DeimosBiomes.DDS~7d678bb (Remastered all biome textures to eliminate DXT errors)" DeimosBiomes.dds
move /y "DioneBiomes.DDS~7d678bb (Remastered all biome textures to eliminate DXT errors)" DioneBiomes.dds
move /y "EarthBiomes.DDS~7d678bb (Remastered all biome textures to eliminate DXT errors)" EarthBiomes.dds
move /y "EnceladusBiomes.DDS~7d678bb (Remastered all biome textures to eliminate DXT errors)" EnceladusBiomes.dds
move /y "EuropaBiomes.DDS~7d678bb (Remastered all biome textures to eliminate DXT errors)" EuropaBiomes.dds
move /y "GanymedeBiomes.DDS~7d678bb (Remastered all biome textures to eliminate DXT errors)" GanymedeBiomes.dds
move /y "IapetusBiomes.DDS~7d678bb (Remastered all biome textures to eliminate DXT errors)" IapetusBiomes.dds
move /y "IoBiomes.DDS~7d678bb (Remastered all biome textures to eliminate DXT errors)" IoBiomes.dds
move /y "JupiterBiomes.DDS~7d678bb (Remastered all biome textures to eliminate DXT errors)" JupiterBiomes.dds
move /y "MarsBiomes.DDS~7d678bb (Remastered all biome textures to eliminate DXT errors)" MarsBiomes.dds
move /y "MercuryBiomes.DDS~7d678bb (Remastered all biome textures to eliminate DXT errors)" MercuryBiomes.dds
move /y "MimasBiomes.DDS~7d678bb (Remastered all biome textures to eliminate DXT errors)" MimasBiomes.dds
move /y "MirandaBiomes.DDS~7d678bb (Remastered all biome textures to eliminate DXT errors)" MirandaBiomes.dds
move /y "MoonBiomes.DDS~7d678bb (Remastered all biome textures to eliminate DXT errors)" MoonBiomes.dds
move /y "NeptuneBiomes.DDS~7d678bb (Remastered all biome textures to eliminate DXT errors)" NeptuneBiomes.dds
move /y "OberonBiomes.DDS~7d678bb (Remastered all biome textures to eliminate DXT errors)" OberonBiomes.dds
move /y "PhobosBiomes.DDS~7d678bb (Remastered all biome textures to eliminate DXT errors)" PhobosBiomes.dds
move /y "PlutoBiomes.DDS~7d678bb (Remastered all biome textures to eliminate DXT errors)" PlutoBiomes.dds
move /y "RheaBiomes.DDS~7d678bb (Remastered all biome textures to eliminate DXT errors)" RheaBiomes.dds
move /y "SaturnBiomes.DDS~7d678bb (Remastered all biome textures to eliminate DXT errors)" SaturnBiomes.dds
move /y "TethysBiomes.DDS~7d678bb (Remastered all biome textures to eliminate DXT errors)" TethysBiomes.dds
move /y "TitanBiomes.DDS~7d678bb (Remastered all biome textures to eliminate DXT errors)" TitanBiomes.dds
move /y "TitaniaBiomes.DDS~7d678bb (Remastered all biome textures to eliminate DXT errors)" TitaniaBiomes.dds
move /y "TritonBiomes.DDS~7d678bb (Remastered all biome textures to eliminate DXT errors)" TritonBiomes.dds
move /y "UmbrielBiomes.DDS~7d678bb (Remastered all biome textures to eliminate DXT errors)" UmbrielBiomes.dds
move /y "UranusBiomes.DDS~7d678bb (Remastered all biome textures to eliminate DXT errors)" UranusBiomes.dds
move /y "VenusBiomes.DDS~7d678bb (Remastered all biome textures to eliminate DXT errors)" VenusBiomes.dds
move /y "VestaBiomes.DDS~7d678bb (Remastered all biome textures to eliminate DXT errors)" VestaBiomes.dds
